name: Tests_V2

on:
  push:
    branches:
      - "main"
      - "dev"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "main"
    tags-ignore:
      - "**"
env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.9"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.4.20
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Metworkpy
        run: |
          if [[ "${{ matrix.python-version }}" == "3.9" || "${{ matrix.python-version }}" == "3.10" ]]; then
            uv pip install ".[gurobi,excel,fastparquet,cplex]"
          else
            uv pip install ".[gurobi,excel,fastparquet]"
          fi
      - name: Install Tools
        run: uv pip install pytest ruff
      - name: Lint with ruff
        run: |
          ruff check --output-format=github ./metworkpy
      - name: Test with Pytest
        run: |
          pytest .
